// Every silhouette has a one-pixel safety margin for jumps and sways.
// Eyes and mouths occupy separate 2x2 regions on a light face, not fixed
// screen coordinates. Patches move ears, tails, wings, or paws per species.
export type Point = readonly [number, number];
export type PixelPatch = readonly [number, number, string];
export interface Artwork {
	pixels: string[];
	face: { eyes: readonly [Point, Point]; mouth: Point };
	motion: readonly PixelPatch[];
}

export const ARTWORK: Record<string, Artwork> = {
	"cache-cat": {
		face: { eyes: [[5, 4], [9, 4]], mouth: [7, 7] },
		motion: [[12, 8, "."], [13, 7, "b"], [13, 8, "o"]],
		pixels: [
			"................",
			"...oo......oo...",
			"...obo....obo...",
			"...obboooobbo...",
			"...ohhhhhhhho...",
			"...ohhhhhhhho...",
			"...ophhhhhipo...",
			"....ohhhhho.....",
			"....obhhbbo.bo..",
			"....obbbbboobo..",
			".....oo..oooo...",
			"................",
		],
	},
	"stack-fox": {
		face: { eyes: [[5, 4], [9, 4]], mouth: [7, 7] },
		motion: [[13, 8, "h"], [13, 9, "s"], [14, 7, "h"]],
		pixels: [
			"................",
			"...o........o...",
			"..oboo....oobo..",
			"...obboooobbo...",
			"...ohhhhhhhho...",
			"...ohhhhhhhho...",
			"....phhhhipo....",
			"....ohhhhho..o..",
			".....ohhho..oho.",
			"....obhhbboohho.",
			"....oo..oossso..",
			"................",
		],
	},
	"byte-dragon": {
		face: { eyes: [[5, 3], [9, 3]], mouth: [7, 6] },
		motion: [[2, 6, "a"], [13, 6, "a"], [2, 8, "."], [13, 8, "."]],
		pixels: [
			"................",
			"....a......a....",
			"...oaobbbboao...",
			"...ohhhhhhhho...",
			"...ohhhhhhhho...",
			"....phhhhipo....",
			"....ohhhhho.....",
			"..ooobhhbbooo...",
			"..obaoohhoaba...",
			"...ooobbbboo.a..",
			".....oo..oooobo.",
			"................",
		],
	},
	"kernel-phoenix": {
		face: { eyes: [[5, 4], [9, 4]], mouth: [7, 7] },
		motion: [[1, 6, "a"], [14, 6, "a"], [2, 8, "."], [13, 8, "."]],
		pixels: [
			"................",
			"......aaa.......",
			".....oaaao......",
			"....obbbbbo.....",
			"...ohhhhhhhho...",
			"...ohhhhhhhho...",
			"....phhhhipo....",
			"..ooohhhhhooo...",
			"..abbbhhbbbba...",
			"....oobbbboo....",
			".....aassaa.....",
			"................",
		],
	},
	"queue-rabbit": {
		face: { eyes: [[5, 5], [9, 5]], mouth: [7, 8] },
		motion: [[4, 1, "."], [5, 1, "b"], [10, 1, "."], [9, 1, "b"]],
		pixels: [
			"................",
			"....oo....oo....",
			"....opo..opo....",
			"....opo..opo....",
			"...obboooobbo...",
			"...ohhhhhhhho...",
			"...ohhhhhhhho...",
			"...ophhhhhipo...",
			"....ohhhhho.....",
			"...obhhhhbbo....",
			"...ooo..oooo....",
			"................",
		],
	},
	"regex-raccoon": {
		face: { eyes: [[5, 4], [9, 4]], mouth: [7, 7] },
		motion: [[13, 8, "s"], [13, 9, "h"], [14, 8, "o"]],
		pixels: [
			"................",
			"....oo....oo....",
			"...ohho..ohho...",
			"...obboooobbo...",
			"...oshhhhhhso...",
			"...oshhhhhhso...",
			"...ophhhhhipo...",
			"....ohhhhho.....",
			"....obhhbbo.oo..",
			"....obbbbbohso..",
			".....oo..oosho..",
			"................",
		],
	},
	"cloud-otter": {
		face: { eyes: [[4, 4], [9, 4]], mouth: [6, 7] },
		motion: [[3, 8, "b"], [11, 8, "b"], [3, 9, "."], [11, 9, "."]],
		pixels: [
			"................",
			"................",
			"...oo.....oo....",
			"..obbooooobbo...",
			"..ohhhhhhhhho...",
			"..ohhhhhhhhho...",
			"..ophhhhhippo...",
			"...ohhhhhho.....",
			"....bhhhhb......",
			"...obhhhhbbo....",
			"....oo..ooobbo..",
			"................",
		],
	},
	"quantum-owl": {
		face: { eyes: [[4, 4], [10, 4]], mouth: [7, 7] },
		motion: [[2, 7, "a"], [13, 7, "a"], [3, 9, "."], [12, 9, "."]],
		pixels: [
			"................",
			"...o........o...",
			"...oboooooobo...",
			"...ohhhohhhho...",
			"...ohhhohhhho...",
			"...ohhhohhhho...",
			"...ophhhhhipo...",
			"...obhhhhbbo....",
			"...obhhhhbbo....",
			"...oabbbbaoo....",
			".....aa..aa.....",
			"................",
		],
	},
};
